#Name : Rory Garner
#Class : Sofward Development
#Year : 4 
#2017-2018
CC = g++
cFlags = -std=c++11 -pthread -o Lab1.cpp
cFiles = signal.cpp Semaphore.cpp
hFiles = Semaphore.h

ALL: $(cFiles) $(hFiles)
	$(CC) $(cFlags) $(cFiles) -o Lab1

CLEAN:
	rm*.o	
